default:

  blynk:

    vpins:

      JOYSTICK: 0 # set to MERGE
      BATT_LARGE: 1

      BRICK_TO_VPIN_VOLT:
        0: &brick0_vpin 2
        1: &brick1_vpin 3
        2: &brick2_vpin 4
        3: &brick3_vpin 5
        4: &brick4_vpin 6
        5: &brick5_vpin 7
        6: &brick6_vpin 8

      BRICK_TO_VPIN_BLEED:
        0: 9
        1: 10
        2: 11
        3: 12
        4: 13
        5: 14
        6: 15

      VPIN_TO_BRICK:
        *brick0_vpin: 0
        *brick1_vpin: 1
        *brick2_vpin: 2
        *brick3_vpin: 3
        *brick4_vpin: 4
        *brick5_vpin: 5
        *brick6_vpin: 6

    BATT_COLOR_HIGH: '#00FF00'
    BATT_COLOR_LOW: '#FF0000'
    BATT_WARNING_P: 20.0 # 20%
    CELL_WARNING_V: 3.25 # 20%
    REFRESH_INTERVAL: 5  # sec
  
  bms:

    pins: null

    # start reducing power coming from motor
    BATT_SHUTDOWN_SOFT_P: 10
    # shutdown electronics and connection to motor
    BATT_SHUTDOWN_HARD_P: 0
    CELL_MIN_V: 3.0  # 0%
    CELL_MAX_V: 4.2  # 100%

  motor:

    pins: null

    # large instantaneous increases in motor speed 
    # will be divided up into smaller chunks for 
    # smoother controller experience
    MOTOR_SPEED_STEP_NUM: 5
    MOTOR_SPEED_STEP_TIME: 100 # ms
